apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamsight-agent.fullname" . }}
  labels:
    {{- include "streamsight-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_BROKERS: {{ .Values.kafka.brokers | quote }}
  API_KEY: {{ .Values.apiKey | quote }}
  {{- if .Values.kafka.sasl.enabled }}
  KAFKA_SASL_MECHANISM: {{ .Values.kafka.sasl.mechanism | quote }}
  KAFKA_SASL_USERNAME: {{ .Values.kafka.sasl.username | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.sasl.password | quote }}
  {{- end }}
  {{- if .Values.kafka.tls.enabled }}
  KAFKA_TLS_ENABLED: "true"
  {{- end }}
